### PR TITLE
remove redundant async threads in migration process

### LINKED ISSUE #1180: migrate workflow - destroy failure step fails to create a user task
when a destroy step fails, the job fails with below exception

05:31:28.014 [thread-pool-8] INFO  o.e.x.m.w.h.m.MigrateDestroyProcess [a13b99eb-92cd-487e-a45a-4c0e47c58f8d]- Process instance: 22544 retry destroy service : 087d5f9c-eace-45ce-90cc-d933062eb856,RetryNum:1
05:31:28.014 [thread-pool-8] INFO  o.e.x.m.w.h.m.MigrateDestroyProcess [a13b99eb-92cd-487e-a45a-4c0e47c58f8d]- Migration workflow start destroying old service with service id:087d5f9c-eace-45ce-90cc-d933062eb856
05:31:28.016 [thread-pool-8] ERROR o.e.x.m.w.h.m.MigrateDestroyProcess [a13b99eb-92cd-487e-a45a-4c0e47c58f8d]- Migration workflow destroy old service with id:087d5f9c-eace-45ce-90cc-d933062eb856 failed. error:org.eclipse.xpanse.modules.models.service.deploy.exceptions.PluginNotFoundException: Can't find suitable plugin and resource handler for the Task.
05:31:28.016 [thread-pool-8] INFO  o.e.x.m.w.h.m.MigrateDestroyProcess [a13b99eb-92cd-487e-a45a-4c0e47c58f8d]- Migration workflow completed destroying old service with id:087d5f9c-eace-45ce-90cc-d933062eb856, success:false
05:31:28.018 [thread-pool-8] ERROR o.a.e.i.interceptor.CommandContext [a13b99eb-92cd-487e-a45a-4c0e47c58f8d]- Error while closing command context
org.activiti.engine.ActivitiException: Unknown property used in expression: ${assignee}
	at org.activiti.engine.impl.el.JuelExpression.getValueFromContext(JuelExpression.java:97)
	at org.activiti.engine.impl.el.JuelExpression.getValue(JuelExpression.java:54)
	at org.activiti.engine.impl.bpmn.behavior.UserTaskActivityBehavior.handleAssignments(UserTaskActivityBehavior.java:290)
	at org.activiti.engine.impl.bpmn.behavior.UserTaskActivityBehavior.execute(UserTaskActivityBehavior.java:225)
	at org.activiti.engine.impl.agenda.ContinueProcessOperation.executeActivityBehavior(ContinueProcessOperation.java:230)
	at org.activiti.engine.impl.agenda.ContinueProcessOperation.executeSynchronous(ContinueProcessOperation.java:168)
	at org.activiti.engine.impl.agenda.ContinueProcessOperation.continueThroughFlowNode(ContinueProcessOperation.java:117)
	at org.activiti.engine.impl.agenda.ContinueProcessOperation.run(ContinueProcessOperation.java:82)
	at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:77)
	at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:61)
	at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:46)
	at org.activiti.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:52)
	at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:63)
	at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:51)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:49)
	at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:33)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:59)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:54)

### LINKED ISSUE #1197: service migration - service entered to DB too late
As part of the  service migration process, we are currently creating the service ID entry in the DB only at the `MigrateDeployProcess` step.  This is not correct because if the workflow fails in the steps before this, then we do not have any way to track this ID. 

- [ ] Create the entry in DB as part of the migrate API request itself. 
- [ ] Start the deployment as part of `MigrateDeployProcess` step.

### LINKED ISSUE #1214: remove redundant async threads in migration process
In the migration process, all unnecessary async threads must be removed. 
The async thread within xpanse is needed only for terraform-local process.

### PR DESCRIPTION
**Pull request by WangLiNaruto**
Fixed  #1180 
Fixed #1197
Fixed #1214

success:
image
image
image

error:
image
image
image
image

### CODE REVIEW

File: modules/api/src/main/java/org/eclipse/xpanse/api/controllers/TerraformBootWebhookApi.java [hunk 1]
```diff
@@ -45,14 +45,16 @@ public class TerraformBootWebhookApi {
...
     @ResponseStatus(HttpStatus.OK)
     public void deployCallback(
             @Parameter(name = "task_id", description = "task id")
-            @PathVariable("task_id") String taskId, @Valid @RequestBody TerraformResult result) {
+            @PathVariable("task_id") String taskId,
+            @Valid @RequestBody TerraformResult result) {
 
-        terraformDeploymentResultCallbackManager.deployCallback(taskId, result);
+        terraformDeploymentResultCallbackManager.deployCallback(taskId, result,
+                result.getProcessInstanceId());
```
Comment (swaroopar) [inline modules/api/src/main/java/org/eclipse/xpanse/api/controllers/TerraformBootWebhookApi.java:57]: there should be no changes to terraform-boot. The "processInstanceId" is internal to xpanse and terraformBoot has no idea about it. 

We must just check if  the taskId has any related old service ID in the migration table. If yes, then we additionally push the workflow for the corresponding migration ID. 

same for destroy.

**Review by swaroopar — CHANGES_REQUESTED** [review]

File: modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/deployment/DeployTask.java [hunk 2]
```diff
@@ -39,4 +39,6 @@ public class DeployTask {
 
     private UUID serviceTemplateId;
 
+    private String processInstanceId;
```
Comment (swaroopar) [inline modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/deployment/DeployTask.java:42]: we do not need this.

File: modules/models/src/main/java/org/eclipse/xpanse/modules/models/response/ResultType.java [hunk 3]
```diff
@@ -55,7 +55,8 @@ public enum ResultType {
     POLICY_EVALUATION_FAILED("Policy Evaluation Failed"),
     USER_NO_LOGIN_EXCEPTION("Current Login User No Found"),
     SERVICE_DETAILS_NOT_ACCESSIBLE("Service Details No Accessible"),
-    ACTIVITI_TASK_NOT_FOUND("Migrating activiti Task Not Found");
+    ACTIVITI_TASK_NOT_FOUND("Migrating activiti Task Not Found"),
+    SERVICE_MIGRATION_EXCEPTION("Service Migration Exception");
```
Comment (swaroopar) [inline modules/models/src/main/java/org/eclipse/xpanse/modules/models/response/ResultType.java:59]: SERVICE_MIGRATION_FAILED_EXCEPTION("Service Migration Failed Exception");

File: modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java [hunk 4]
```diff
@@ -283,39 +282,35 @@ private void purgeService(DeployTask deployTask, DeployServiceEntity deployServi
     /**
      * Deployment service.
      *
-     * @param newId         new service id.
-     * @param userId        user id.
-     * @param deployRequest deploy request.
-     * @return new deployed service entity.
+     * @param processInstanceId ProcessInstance ID
```
Comment (swaroopar) [inline modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java:285]: we do not need processInstanceId.. it must be transparent to the new service deployer.

**Review by swaroopar — CHANGES_REQUESTED** [review]

**Comment by swaroopar** [comment]
@WangLiNaruto please also fix the compile errors.

File: modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/migration/MigrationService.java [hunk 5]
```diff
@@ -0,0 +1,96 @@
...
+     *
+     * @param taskId newServiceId.
+     * @return ServiceMigrationEntity.
+     */
+    public ServiceMigrationEntity getServiceMigrationEntityByNewServiceId(String taskId) {
+        List<ServiceMigrationEntity> serviceMigrationEntities =
+                serviceMigrationStorage.serviceMigrations().stream()
+                        .filter(serviceMigrationEntity -> taskId.equals(
+                                serviceMigrationEntity.getNewServiceId().toString()))
+                        .collect(Collectors.toList());
```
Comment (swaroopar) [inline modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/migration/MigrationService.java:71]: `.collect(Collectors.toList()); ` -> can be replaced with just `.toList();`

File: modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/migration/MigrationService.java [hunk 6]
```diff
@@ -0,0 +1,96 @@
...
+     *
+     * @param taskId oldServiceId.
+     * @return ServiceMigrationEntity.
+     */
+    public ServiceMigrationEntity getServiceMigrationEntityByOldServiceId(String taskId) {
+        List<ServiceMigrationEntity> serviceMigrationEntities =
+                serviceMigrationStorage.serviceMigrations().stream()
+                        .filter(serviceMigrationEntity -> taskId.equals(
+                                serviceMigrationEntity.getOldServiceId().toString()))
+                        .collect(Collectors.toList());
```
Comment (swaroopar) [inline modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/migration/MigrationService.java:90]: `.collect(Collectors.toList()); ` -> can be replaced with just `.toList();`

File: modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/migration/handler/CheckDeployStatus.java [hunk 7]
```diff
@@ -0,0 +1,107 @@
+/*
+ * SPDX-License-Identifier: Apache-2.0
+ * SPDX-FileCopyrightText: Huawei Inc.
+ *
+ */
+
+package org.eclipse.xpanse.modules.deployment.migration.handler;
```
Comment (swaroopar) [inline modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/migration/handler/CheckDeployStatus.java:7]: the package name can be "steps" instead of "handler".

File: modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/migration/handler/CheckDeployStatus.java [hunk 8]
```diff
@@ -0,0 +1,107 @@
...
+import org.eclipse.xpanse.modules.models.workflow.migrate.enums.MigrationStatus;
+import org.springframework.beans.factory.annotation.Autowired;
+import org.springframework.stereotype.Component;
+
+/**
+ * Processing class for checking deployment status after deployment callback.
+ */
+@Slf4j
+@Component
+public class CheckDeployStatus implements Serializable, JavaDelegate {
```
Comment (swaroopar) [inline modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/migration/handler/CheckDeployStatus.java:33]: class name can be - ProcessDeploymentResult

File: modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/migration/handler/CheckDestroyStatus.java [hunk 9]
```diff
@@ -0,0 +1,140 @@
...
+import org.eclipse.xpanse.modules.models.workflow.migrate.enums.MigrationStatus;
+import org.springframework.beans.factory.annotation.Autowired;
+import org.springframework.stereotype.Component;
+
+/**
+ * Processing class for checking destroy status after destroy callback.
+ */
+@Slf4j
+@Component
+public class CheckDestroyStatus implements Serializable, JavaDelegate {
```
Comment (swaroopar) [inline modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/migration/handler/CheckDestroyStatus.java:33]: class name can be - ProcessDestroytResult

**Review by swaroopar — CHANGES_REQUESTED** [review]

**Review by swaroopar — APPROVED** [review]
LGTM
