### PR TITLE
fix monitor for HuaweiCloud and FlexibleEngine

### LINKED ISSUE #800: Metrics for HuaweiCloud need to be updated
# Metrics for HuaweiCloud need to be updated

image

image

### PR DESCRIPTION
**Pull request by jinyangyang222**
fixes #800

### CODE REVIEW

File: plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/monitor/utils/FlexibleEngineMetricsService.java [hunk 1]
```diff
@@ -339,9 +339,16 @@ private Map<MonitorResourceType, MetricInfoList> getTargetMetricsMap(
...
-        }
-        return targetMetricsMap;
+            return targetMetricsMap;
 
+        } else {
+            log.error(
+                    "No monitor metrics available for the service, "
+                            + "Please wait for 3-5 minutes and try again.");
+            throw new ClientApiCallFailedException(
+                    "No monitor metrics available for the  service, "
```
Comment (swaroopar) [inline plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/monitor/utils/FlexibleEngineMetricsService.java:349]: looks like there is an extra space before the word "service". Same in both places.

File: plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/monitor/utils/FlexibleEngineMetricsService.java [hunk 2]
```diff
@@ -339,9 +339,16 @@ private Map<MonitorResourceType, MetricInfoList> getTargetMetricsMap(
...
             }
-        }
-        return targetMetricsMap;
+            return targetMetricsMap;
 
+        } else {
+            log.error(
+                    "No monitor metrics available for the service, "
+                            + "Please wait for 3-5 minutes and try again.");
+            throw new ClientApiCallFailedException(
```
Comment (swaroopar) [inline plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/monitor/utils/FlexibleEngineMetricsService.java:348]: ClientApiCallFailedException -> will return HTTP code 502 to client which is not correct. 
If we really need an exception to be returned here, then we must define something new that will return HTTP 400.

**Review by swaroopar — CHANGES_REQUESTED** [review]
pls check the exception type.

**Review by swaroopar — APPROVED** [review]
LGTM
