### PR TITLE
Fix Migration service workflow blocked in the service deployment task

### LINKED ISSUE #1065: Fix Migration service workflow blocked in the service deployment task
The Migration service workflow blocked in the service deployment task. The new service instance was already but the old one cloud not be destroyed.
image
image
Caused by the `NullPointerException` :
image

### PR DESCRIPTION
**Pull request by baixinsui**
fixes #1065

### CODE REVIEW

File: modules/workflow/src/main/java/org/eclipse/xpanse/modules/workflow/handle/migrate/MigrateDeployProcess.java [hunk 1]
```diff
@@ -35,12 +38,12 @@ public class MigrateDeployProcess implements Serializable, JavaDelegate {
 
     @Autowired
     public void setRuntimeService(RuntimeService runtimeService) {
-        this.runtimeService = runtimeService;
+        MigrateDeployProcess.runtimeService = runtimeService;
```
Comment (swaroopar) [inline modules/workflow/src/main/java/org/eclipse/xpanse/modules/workflow/handle/migrate/MigrateDeployProcess.java:41]: @baixinsui I believe it better to keep all autowired beans as non-static. I had actually given the same comment when the original PR was opened as well. 
Could you please make the change to MigrateDeployProcess and MigrateDestroyProcess?

**Review by swaroopar — CHANGES_REQUESTED** [review]

File: modules/workflow/src/main/java/org/eclipse/xpanse/modules/workflow/handle/migrate/MigrateDeployProcess.java (hunk 1 above)
Comment (baixinsui) [reply modules/workflow/src/main/java/org/eclipse/xpanse/modules/workflow/handle/migrate/MigrateDeployProcess.java]: @swaroopar The workflow engine couldn't instantiate class after I change the static class to autowired bean.
image
