### PR TITLE
return error when exception occurs

### LINKED ISSUE #417: Service Destroy - Returns success always
the service destroy method currently returns success always. 
The exceptions are simply ignored.

### PR DESCRIPTION
**Pull request by swaroopar**
fixes #417

### CODE REVIEW

File: modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironments.java [hunk 1]
```diff
@@ -12,21 +12,20 @@
 import org.eclipse.xpanse.modules.models.enums.DeployVariableKind;
 import org.eclipse.xpanse.modules.models.resource.DeployVariable;
 import org.eclipse.xpanse.modules.models.resource.Flavor;
+import org.springframework.stereotype.Component;
 
 /**
  * Environment variables utils for deployment.
  */
+@Component
```
Comment (iskey) [inline modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironments.java:20]: I think no need to make `DeployEnvironments` a `Component`, The methods here are sort of helpers for environments variables, no need to create an object.

File: modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironments.java [hunk 2]
```diff
@@ -12,21 +12,20 @@
...
-    private DeployEnvironments() {
-    }
-
     /**
      * Get environment variables for deployment.
      *
      * @param task the context of the task.
      */
-    public static Map<String, String> getEnv(DeployTask task) {
+    public Map<String, String> getEnv(DeployTask task) {
```
Comment (iskey) [inline modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironments.java:28]: I feel like better to keep it as-is .

**Review by iskey — CHANGES_REQUESTED** [review]
some minor comments added.

File: modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironments.java (hunk 1 above)
Comment (swaroopar) [reply modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironments.java:20]: @iskey I made it a component so that it is possible to mock and test it without too much efforts. 
And it is also a singleton (by default) so no overhead we have here.

File: modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironments.java (hunk 2 above)
Comment (swaroopar) [reply modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironments.java:28]: same here.

File: modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironments.java (hunk 1 above)
Comment (iskey) [reply modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironments.java:20]: Ok, It makes sense, but I feel it is a bit strange always.

**Review by iskey — APPROVED** [review]
looks good.
