### PR TITLE
fix CredentialApi

### LINKED ISSUE #473: Fix CredentialApi
1.Constructor error in CredentiaVariables class.
2.Add check xpanseUser is not null.

### PR DESCRIPTION
**Pull request by jinyangyang222**
fixed #473

### CODE REVIEW

**Comment by swaroopar** [comment]
@jinyangyang222 pls fix merge conflicts

File: modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialCenter.java [hunk 1]
```diff
@@ -131,6 +131,9 @@ public String getCredentialOpenApiUrl(Csp csp, CredentialType type) {
      * @return the credentials.
      */
     public List<AbstractCredentialInfo> getCredentialsByUser(String xpanseUser) {
+        if (StringUtils.isBlank(xpanseUser)) {
```
Comment (swaroopar) [inline modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialCenter.java:134]: Hi @jinyangyang222 
in the getCredentialsByUser  API method -> we can make user parameter as "required".
And here instead of returning null, we must return empty list.

**Review by swaroopar — CHANGES_REQUESTED** [review]
comments added.

**Review by swaroopar — APPROVED** [review]
LGTM
